config/routes.rb
Rails.application.routes.draw do
  get 'tagihans/new_form'
  resources :tagihans
  resources :daftar_muatans
  resources :kendaraans
  resources :hargas
  resources :konsumen

end

app/models/daftar_muatan.rb
class DaftarMuatan < ActiveRecord::Base
  has_many :muatan_items
  belongs_to :kendaraan
end

app/controllers/daftar_muatans_controller.rb
class DaftarMuatansController < ApplicationController
  before_action :set_daftar_muatan, only: [:show, :edit, :update, :destroy]

  # GET /daftar_muatans
  # GET /daftar_muatans.json
  def index
    @daftar_muatans = DaftarMuatan.paginate(page: params[:page], per_page: 20)
  end

  # GET /daftar_muatans/1
  # GET /daftar_muatans/1.json
  def show
  end

  # GET /daftar_muatans/new
  def new
    @daftar_muatan = DaftarMuatan.new
    @kendaraan = Kendaraan.all
    @harga = Harga.all
    @konsuman = Konsuman.all
    @arr = []

    (1..15).each do |i|
      @arr << MuatanItem.new
    end
  end

  # GET /daftar_muatans/1/edit
  def edit
    @kendaraan = Kendaraan.all
    @harga = Harga.all
    @konsuman = Konsuman.all
    @arr = []

    i = 1
    @daftar_muatan.muatan_items.each do |muatan_item|
      @arr << muatan_item
    end

    (i..15).each do |i|
      @arr << MuatanItem.new
    end
  end

  # POST /daftar_muatans
  # POST /daftar_muatans.json
  def create
    @daftar_muatan = DaftarMuatan.new(daftar_muatan_params)

    respond_to do |format|
      if @daftar_muatan.save
        @daftar_muatan.reload
        (1..15).each do |i|
          break if params[("no_do_" + i.to_s).to_sym].blank?
          MuatanItem.create(
            no_do: params[("no_do_" + i.to_s).to_sym],
            konsumen_id: params[("konsumen_id_" + i.to_s).to_sym],
            tambahan: params[("tambahan_" + i.to_s).to_sym],
            daftar_muatan_id: @daftar_muatan.id
          )
        end
        format.html { redirect_to @daftar_muatan, notice: 'Daftar muatan was successfully created.' }
        format.json { render :show, status: :created, location: @daftar_muatan }
      else
        format.html { render :new }
        format.json { render json: @daftar_muatan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daftar_muatans/1
  # PATCH/PUT /daftar_muatans/1.json
  def update
    respond_to do |format|
      if @daftar_muatan.update(daftar_muatan_params)
        @daftar_muatan.reload
        @daftar_muatan.muatan_items.delete_all
        (1..15).each do |i|
          break if params[("no_do_" + i.to_s).to_sym].blank?
          MuatanItem.create(
            no_do: params[("no_do_" + i.to_s).to_sym],
            konsumen_id: params[("konsumen_id_" + i.to_s).to_sym],
            tambahan: params[("tambahan_" + i.to_s).to_sym],
            daftar_muatan_id: @daftar_muatan.id
          )
        end
        format.html { redirect_to @daftar_muatan, notice: 'Daftar muatan was successfully updated.' }
        format.json { render :show, status: :ok, location: @daftar_muatan }
      else
        format.html { render :edit }
        format.json { render json: @daftar_muatan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daftar_muatans/1
  # DELETE /daftar_muatans/1.json
  def destroy
    @daftar_muatan.muatan_items.delete_all
    @daftar_muatan.destroy
    respond_to do |format|
      format.html { redirect_to daftar_muatans_url, notice: 'Daftar muatan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daftar_muatan
      @daftar_muatan = DaftarMuatan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daftar_muatan_params
      params.require(:daftar_muatan).permit(:customer_name, :kendaraan_id, :no_dm, :tgl_kirim, :kota, :harga, :tambahan, :tgl_terima)
    end
end

app/helpers/daftar_muatans_helper.rb
module DaftarMuatansHelper
end

app/views/daftar_muatans/_form.html.erb
<%= form_for(@daftar_muatan) do |f| %>
  <% if @daftar_muatan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daftar_muatan.errors.count, "error") %> prohibited this daftar_muatan from being saved:</h2>

      <ul>
      <% @daftar_muatan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :customer_name %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.select :customer_name, ["PT. ROYAL SULTAN AGUNG JKT", "PT. ROYAL SULTAN AGUNG SBY"], {}, {:class=> "w3-select w3-border w3-small"} %>
  </div>
  <div class="w3-col s3 w3-right-align">
    <%= f.label :kendaraan_id %>&nbsp;
  </div>
  <div class="w3-col s3">
    <select name="daftar_muatan[kendaraan_id]" id="kendaraan_id" class="w3-select w3-border w3-small">
    <% @kendaraan.each do |kendaraan| %>
       <option value="<%= kendaraan.id %>"><%= kendaraan.supir %> - <%= kendaraan.no_kendaraan %></option>
    <% end %>
    </select>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :no_dm %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.text_field :no_dm, :class=> "w3-input w3-border w3-small" %>
  </div>
  <div class="w3-col s3 w3-right-align">
    <%= f.label :tgl_kirim %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.date_select :tgl_kirim, order: [:day, :month, :year] %>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :kota %>&nbsp;
  </div>
  <div class="w3-col s3">
    <select name="daftar_muatan[kota]" id="kota" onchange='myFunction()' class="w3-select w3-border w3-small">
    <% @harga.each do |harga| %>
       <option value="<%= harga.kota_tujuan %>" <% if harga.kota_tujuan == @daftar_muatan.kota %>selected<% end %>><%= harga.kota_tujuan %> - <%= harga.tarif %></option>
    <% end %>
    </select>
  </div>
  <div class="w3-col s3 w3-right-align">
    <%= f.label :harga %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.text_field :harga, :class=> "w3-input w3-border w3-small" %>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :tambahan %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.text_field :tambahan, :class=> "w3-input w3-border w3-small" %>
  </div>
  <div class="w3-col s3 w3-right-align">
    <%= f.label :tgl_terima %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.date_select :tgl_terima, order: [:day, :month, :year] %>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3">
    &nbsp;
  </div>
  <div class="w3-col s3">
    <br>
    <%= f.submit %>
  </div>
  </div>
  <br>
  <table class="w3-table-all w3-hoverable">
  <thead>
    <tr class="w3-light-grey">
      <th>Nomor DO</th>
      <th>Customer</th>
      <th>Tambahan</th>
    </tr>
  </thead>

  <tbody>
    <% @arr.each_with_index do |muatan_item, idx| %>
    <tr>
      <td><input type="text" name="no_do_<%=idx+1%>"value="<%=muatan_item.no_do%>" class="w3-input w3-border w3-small"></td>
      <td>
        <select name="konsumen_id_<%=idx+1%>" class="w3-select w3-border w3-small">
        <% @konsuman.each do |konsuman| %>
           <option value="<%= konsuman.id %>" <% if konsuman.id == muatan_item.konsumen_id %>selected<% end %>><%= konsuman.name %></option>
        <% end %>
        </select>
      </td>
      <td><input type="text" name="tambahan_<%=idx+1%>" value="<%=muatan_item.tambahan%>" class="w3-input w3-border w3-small"></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<script>
  function myFunction() {
    idx = document.getElementById("kota").selectedIndex;
    arr = [<%= @harga.collect(&:tarif).join(",") %>];
    document.getElementById("daftar_muatan_harga").value = arr[idx];
  }
</script>

app/views/daftar_muatans/edit.html.erb
<h1>Editing Daftar Muatan</h1>

<%= render 'form' %>

<%= link_to 'Show', @daftar_muatan %> |
<%= link_to 'Back', daftar_muatans_path %>

app/views/daftar_muatans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Daftar Muatans</h1>

<table class="w3-table-all w3-hoverable">
  <thead>
    <tr class="w3-light-grey">
      <th>Customer name</th>
      <th>Kendaraan</th>
      <th>No dm</th>
      <th>Tgl kirim</th>
      <th>Kota</th>
      <th>Harga</th>
      <th>Tambahan</th>
      <th>Tgl terima</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daftar_muatans.each do |daftar_muatan| %>
      <tr>
        <td><%= daftar_muatan.customer_name %></td>
        <td><%= daftar_muatan.kendaraan.try(:no_kendaraan) %> - <%= daftar_muatan.kendaraan.try(:supir) %></td>
        <td><%= daftar_muatan.no_dm %></td>
        <td><%= daftar_muatan.tgl_kirim %></td>
        <td><%= daftar_muatan.kota %></td>
        <td><%= daftar_muatan.harga %></td>
        <td><%= daftar_muatan.tambahan %></td>
        <td><%= daftar_muatan.tgl_terima %></td>
        <td><%= link_to 'Show', daftar_muatan %></td>
        <td><%= link_to 'Edit', edit_daftar_muatan_path(daftar_muatan) %></td>
        <td><%= link_to 'Destroy', daftar_muatan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="w3-center">
<%= will_paginate @daftar_muatans %>
</div>
<br>

<%= link_to 'New Daftar muatan', new_daftar_muatan_path %>

app/views/daftar_muatans/new.html.erb
<h1>New Daftar Muatan</h1>

<%= render 'form' %>

<%= link_to 'Back', daftar_muatans_path %>

app/views/daftar_muatans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @daftar_muatan.id %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @daftar_muatan.customer_name %>
</p>

<p>
  <strong>Kendaraan:</strong>
  <%= @daftar_muatan.kendaraan_id %>
</p>

<p>
  <strong>No dm:</strong>
  <%= @daftar_muatan.no_dm %>
</p>

<p>
  <strong>Tgl kirim:</strong>
  <%= @daftar_muatan.tgl_kirim %>
</p>

<p>
  <strong>Kota:</strong>
  <%= @daftar_muatan.kota %>
</p>

<p>
  <strong>Harga:</strong>
  <%= @daftar_muatan.harga %>
</p>

<p>
  <strong>Tambahan:</strong>
  <%= @daftar_muatan.tambahan %>
</p>

<p>
  <strong>Tgl terima:</strong>
  <%= @daftar_muatan.tgl_terima %>
</p>

<%= link_to 'Edit', edit_daftar_muatan_path(@daftar_muatan) %> |
<%= link_to 'Back', daftar_muatans_path %>