config/routes.rb
Rails.application.routes.draw do
  get 'tagihans/new_form'
  resources :tagihans
  resources :daftar_muatans
  resources :kendaraans
  resources :hargas
  resources :konsumen

end

app/models/tagihan.rb
class Tagihan < ActiveRecord::Base
  attr_accessor :from_date
  attr_accessor :thru_date
  has_many :daftar_muatans
end

app/controllers/tagihans_controller.rb
class TagihansController < ApplicationController
  before_action :set_tagihan, only: [:show, :edit, :update, :destroy]

  # GET /tagihans
  # GET /tagihans.json
  def index
    @tagihans = Tagihan.paginate(page: params[:page], per_page: 20)
  end

  # GET /tagihans/1
  # GET /tagihans/1.json
  def show
  end

  # GET /tagihans/new
  def new
    @tagihan = Tagihan.new
    from_date = params.require(:tagihan).permit(:from_date).to_hash
    thru_date = params.require(:tagihan).permit(:thru_date).to_hash
    from_date = from_date["from_date(1i)"] + "-" + from_date["from_date(2i)"] + "-" + from_date["from_date(3i)"]
    thru_date = thru_date["thru_date(1i)"] + "-" + thru_date["thru_date(2i)"] + "-" + thru_date["thru_date(3i)"]
    @daftar_muatans = DaftarMuatan.joins(:kendaraan).where("tagihan_id IS NULL AND tgl_kirim BETWEEN '#{from_date}' AND '#{thru_date}'").order("kendaraans.tipe")
    today = Date.today
    count = DaftarMuatan.where("TO_CHAR(tgl_kirim, 'YYYY-MM') = '#{today.strftime("%Y-%m")}'").count + 1
    @tagihan.no_tagihan = count.to_s.rjust(3, "0") + "/" + today.month.to_s.rjust(2, "0") + "/UT/" + today.year.to_s
    @tagihan.customer_name = params.require(:tagihan).permit(:customer_name)[:customer_name]
  end

  def new_form
    @tagihan = Tagihan.new
  end

  # GET /tagihans/1/edit
  def edit
    @daftar_muatans = @tagihan.daftar_muatans.joins(:kendaraan).order("kendaraans.tipe")
  end

  # POST /tagihans
  # POST /tagihans.json
  def create
    @tagihan = Tagihan.new(tagihan_params)
    respond_to do |format|
      if @tagihan.save
        @tagihan.reload
        idx = 1
        while params[("dm_id_" + idx.to_s).to_sym].present? do
          dm = DaftarMuatan.find(params[("dm_id_" + idx.to_s).to_sym])
          dm.update!(tagihan_id: @tagihan.id)
          idx = idx + 1
        end
        format.html { redirect_to @tagihan, notice: 'Tagihan was successfully created.' }
        format.json { render :show, status: :created, location: @tagihan }
      else
        format.html { render :new }
        format.json { render json: @tagihan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tagihans/1
  # PATCH/PUT /tagihans/1.json
  def update
    respond_to do |format|
      if @tagihan.update(tagihan_params)
        format.html { redirect_to @tagihan, notice: 'Tagihan was successfully updated.' }
        format.json { render :show, status: :ok, location: @tagihan }
      else
        format.html { render :edit }
        format.json { render json: @tagihan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tagihans/1
  # DELETE /tagihans/1.json
  def destroy
    DaftarMuatan.where(tagihan_id: @tagihan.id).update_all(tagihan_id: nil)
    @tagihan.destroy
    respond_to do |format|
      format.html { redirect_to tagihans_url, notice: 'Tagihan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tagihan
      @tagihan = Tagihan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tagihan_params
      params.require(:tagihan).permit(:customer_name, :no_tagihan, :tgl_tagihan)
    end
end

app/helpers/tagihans_helper.rb
module TagihansHelper
end

app/views/tagihans/_form.html.erb
<%= form_for(@tagihan) do |f| %>
  <% if @tagihan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tagihan.errors.count, "error") %> prohibited this tagihan from being saved:</h2>

      <ul>
      <% @tagihan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :customer_name %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= @tagihan.customer_name %>
    <%= f.hidden_field :customer_name %>
  </div>
  <div class="w3-col s3 w3-right-align">
    <%= f.label :no_tagihan %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.text_field :no_tagihan %>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3 w3-right-align">
    <%= f.label :tgl_tagihan %>&nbsp;
  </div>
  <div class="w3-col s3">
    <%= f.date_select :tgl_tagihan, order: [:day, :month, :year] %>
  </div>
  </div>
  <div class="w3-row-padding">
  <div class="w3-col s3">
    &nbsp;
  </div>
  <div class="w3-col s3">
    <br>
    <%= f.submit %>
  </div>
  </div>
  <br>
<table class="w3-table-all w3-hoverable">
  <thead>
    <tr class="w3-light-grey">
      <th>Nomor DM</th>
      <th>Tipe Kendaraan</th>
      <th>Kota</th>
      <th>Tgl Kirim</th>
      <th>Tgl Terima</th>
      <th>Harga</th>
      <th>Tambahan</th>
    </tr>
  </thead>

  <tbody>
    <% @daftar_muatans.each_with_index do |daftar_muatan, idx| %>
    <tr>
      <td>
        <%= daftar_muatan.no_dm %>
        <input type="hidden" name="dm_id_<%=idx+1%>" value="<%= daftar_muatan.id %>">
      </td>
      <td><%= daftar_muatan.kendaraan.tipe %></td>
      <td><%= daftar_muatan.kota %></td>
      <td><%= daftar_muatan.tgl_kirim.strftime("%d-%m-%Y") %></td>
      <td><%= daftar_muatan.tgl_terima.strftime("%d-%m-%Y") %></td>
      <td><%= daftar_muatan.harga %></td>
      <td><%= daftar_muatan.tambahan.to_f + daftar_muatan.muatan_items.sum(:tambahan).to_f %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/tagihans/edit.html.erb
<h1>Editing Tagihan</h1>

<%= render 'form' %>

<%= link_to 'Show', @tagihan %> |
<%= link_to 'Back', tagihans_path %>

app/views/tagihans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tagihans</h1>

<table class="w3-table-all w3-hoverable">
  <thead>
    <tr class="w3-light-grey">
      <th>Customer name</th>
      <th>No tagihan</th>
      <th>Tgl tagihan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tagihans.each do |tagihan| %>
      <tr>
        <td><%= tagihan.customer_name %></td>
        <td><%= tagihan.no_tagihan %></td>
        <td><%= tagihan.tgl_tagihan %></td>
        <td><%= link_to 'Show', tagihan %></td>
        <td><%= link_to 'Edit', edit_tagihan_path(tagihan) %></td>
        <td><%= link_to 'Destroy', tagihan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="w3-center">
<%= will_paginate @tagihans %>
</div>
<br>

<%= link_to 'New Tagihan', '/tagihans/new_form' %>

app/views/tagihans/new.html.erb
<h1>New Tagihan</h1>

<%= render 'form' %>

<%= link_to 'Back', tagihans_path %>

app/views/tagihans/new_form.html.erb
<%= form_for(@tagihan, url: {action: 'new'}, method: "get") do |f| %>
<h1>New Tagihan</h1>

<div class="w3-row-padding">
<div class="w3-col s3 w3-right-align">
<%= f.label :customer_name %>&nbsp;
</div>
<div class="w3-col s3">
<%= f.select :customer_name, ["PT. ROYAL SULTAN AGUNG JKT", "PT. ROYAL SULTAN AGUNG SBY"], {}, {:class=> "w3-select w3-border w3-small"} %>
</div>
</div>
<div class="w3-row-padding">
<div class="w3-col s3 w3-right-align">
<%= f.label :from_date %>&nbsp;
</div>
<div class="w3-col s3">
<%= f.date_select :from_date, order: [:day, :month, :year] %>
</div>
<div class="w3-col s3 w3-right-align">
<%= f.label :thru_date %>&nbsp;
</div>
<div class="w3-col s3">
<%= f.date_select :thru_date, order: [:day, :month, :year] %>
</div>
</div>
<div class="w3-row-padding">
<div class="w3-col s3">
&nbsp;
</div>
<div class="w3-col s3">
<br>
<%= f.submit %>
</div>
</div>
<br>
<% end %>
<%= link_to 'Back', tagihans_path %>

app/views/tagihans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tagihan.id %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @tagihan.customer_name %>
</p>

<p>
  <strong>No tagihan:</strong>
  <%= @tagihan.no_tagihan %>
</p>

<p>
  <strong>Tgl tagihan:</strong>
  <%= @tagihan.tgl_tagihan %>
</p>

<%= link_to 'Edit', edit_tagihan_path(@tagihan) %> |
<%= link_to 'Back', tagihans_path %>