config/routes.rb
Rails.application.routes.draw do
  get 'tagihans/new_form'
  resources :tagihans
  resources :daftar_muatans
  resources :kendaraans
  resources :hargas
  resources :konsumen

end

app/models/kendaraan.rb
class Kendaraan < ActiveRecord::Base
end

app/controllers/kendaraans_controller.rb
class KendaraansController < ApplicationController
  before_action :set_kendaraan, only: [:show, :edit, :update, :destroy]

  # GET /kendaraans
  # GET /kendaraans.json
  def index
    @kendaraans = Kendaraan.all
  end

  # GET /kendaraans/1
  # GET /kendaraans/1.json
  def show
  end

  # GET /kendaraans/new
  def new
    @kendaraan = Kendaraan.new
  end

  # GET /kendaraans/1/edit
  def edit
  end

  # POST /kendaraans
  # POST /kendaraans.json
  def create
    @kendaraan = Kendaraan.new(kendaraan_params)

    respond_to do |format|
      if @kendaraan.save
        format.html { redirect_to @kendaraan, notice: 'Kendaraan was successfully created.' }
        format.json { render :show, status: :created, location: @kendaraan }
      else
        format.html { render :new }
        format.json { render json: @kendaraan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kendaraans/1
  # PATCH/PUT /kendaraans/1.json
  def update
    respond_to do |format|
      if @kendaraan.update(kendaraan_params)
        format.html { redirect_to @kendaraan, notice: 'Kendaraan was successfully updated.' }
        format.json { render :show, status: :ok, location: @kendaraan }
      else
        format.html { render :edit }
        format.json { render json: @kendaraan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kendaraans/1
  # DELETE /kendaraans/1.json
  def destroy
    @kendaraan.destroy
    respond_to do |format|
      format.html { redirect_to kendaraans_url, notice: 'Kendaraan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kendaraan
      @kendaraan = Kendaraan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kendaraan_params
      params.require(:kendaraan).permit(:no_kendaraan, :tipe, :supir)
    end
end

app/helpers/kendaraans_helper.rb
module KendaraansHelper
end

app/views/kendaraans/_form.html.erb
<%= form_for(@kendaraan) do |f| %>
  <% if @kendaraan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kendaraan.errors.count, "error") %> prohibited this kendaraan from being saved:</h2>

      <ul>
      <% @kendaraan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_kendaraan %><br>
    <%= f.text_field :no_kendaraan %>
  </div>
  <div class="field">
    <%= f.label :tipe %><br>
    <%= f.text_field :tipe %>
  </div>
  <div class="field">
    <%= f.label :supir %><br>
    <%= f.text_field :supir %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kendaraans/edit.html.erb
<h1>Editing Kendaraan</h1>

<%= render 'form' %>

<%= link_to 'Show', @kendaraan %> |
<%= link_to 'Back', kendaraans_path %>

app/views/kendaraans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kendaraans</h1>

<table>
  <thead>
    <tr>
      <th>No kendaraan</th>
      <th>Tipe</th>
      <th>Supir</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kendaraans.each do |kendaraan| %>
      <tr>
        <td><%= kendaraan.no_kendaraan %></td>
        <td><%= kendaraan.tipe %></td>
        <td><%= kendaraan.supir %></td>
        <td><%= link_to 'Show', kendaraan %></td>
        <td><%= link_to 'Edit', edit_kendaraan_path(kendaraan) %></td>
        <td><%= link_to 'Destroy', kendaraan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kendaraan', new_kendaraan_path %>

app/views/kendaraans/new.html.erb
<h1>New Kendaraan</h1>

<%= render 'form' %>

<%= link_to 'Back', kendaraans_path %>

app/views/kendaraans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @kendaraan.id %>
</p>

<p>
  <strong>No kendaraan:</strong>
  <%= @kendaraan.no_kendaraan %>
</p>

<p>
  <strong>Tipe:</strong>
  <%= @kendaraan.tipe %>
</p>

<p>
  <strong>Supir:</strong>
  <%= @kendaraan.supir %>
</p>

<%= link_to 'Edit', edit_kendaraan_path(@kendaraan) %> |
<%= link_to 'Back', kendaraans_path %>