config/routes.rb
Rails.application.routes.draw do
  get 'tagihans/new_form'
  resources :tagihans
  resources :daftar_muatans
  resources :kendaraans
  resources :hargas
  resources :konsumen

end

app/models/harga.rb
class Harga < ActiveRecord::Base
end

app/controllers/hargas_controller.rb
class HargasController < ApplicationController
  before_action :set_harga, only: [:show, :edit, :update, :destroy]

  # GET /hargas
  # GET /hargas.json
  def index
    @hargas = Harga.all
  end

  # GET /hargas/1
  # GET /hargas/1.json
  def show
  end

  # GET /hargas/new
  def new
    @harga = Harga.new
  end

  # GET /hargas/1/edit
  def edit
  end

  # POST /hargas
  # POST /hargas.json
  def create
    @harga = Harga.new(harga_params)

    respond_to do |format|
      if @harga.save
        format.html { redirect_to @harga, notice: 'Harga was successfully created.' }
        format.json { render :show, status: :created, location: @harga }
      else
        format.html { render :new }
        format.json { render json: @harga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hargas/1
  # PATCH/PUT /hargas/1.json
  def update
    respond_to do |format|
      if @harga.update(harga_params)
        format.html { redirect_to @harga, notice: 'Harga was successfully updated.' }
        format.json { render :show, status: :ok, location: @harga }
      else
        format.html { render :edit }
        format.json { render json: @harga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hargas/1
  # DELETE /hargas/1.json
  def destroy
    @harga.destroy
    respond_to do |format|
      format.html { redirect_to hargas_url, notice: 'Harga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_harga
      @harga = Harga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def harga_params
      params.require(:harga).permit(:kota_tujuan, :tarif, :ongkos)
    end
end

app/helpers/hargas_helper.rb
module HargasHelper
end

app/views/hargas/_form.html.erb
<%= form_for(@harga) do |f| %>
  <% if @harga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@harga.errors.count, "error") %> prohibited this harga from being saved:</h2>

      <ul>
      <% @harga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kota_tujuan %><br>
    <%= f.text_field :kota_tujuan %>
  </div>
  <div class="field">
    <%= f.label :tarif %><br>
    <%= f.text_field :tarif %>
  </div>
  <div class="field">
    <%= f.label :ongkos %><br>
    <%= f.text_field :ongkos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hargas/edit.html.erb
<h1>Editing Harga</h1>

<%= render 'form' %>

<%= link_to 'Show', @harga %> |
<%= link_to 'Back', hargas_path %>

app/views/hargas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hargas</h1>

<table>
  <thead>
    <tr>
      <th>Kota tujuan</th>
      <th>Tarif</th>
      <th>Ongkos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hargas.each do |harga| %>
      <tr>
        <td><%= harga.kota_tujuan %></td>
        <td><%= harga.tarif %></td>
        <td><%= harga.ongkos %></td>
        <td><%= link_to 'Show', harga %></td>
        <td><%= link_to 'Edit', edit_harga_path(harga) %></td>
        <td><%= link_to 'Destroy', harga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Harga', new_harga_path %>

app/views/hargas/new.html.erb
<h1>New Harga</h1>

<%= render 'form' %>

<%= link_to 'Back', hargas_path %>

app/views/hargas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @harga.id %>
</p>

<p>
  <strong>Kota tujuan:</strong>
  <%= @harga.kota_tujuan %>
</p>

<p>
  <strong>Tarif:</strong>
  <%= @harga.tarif %>
</p>

<p>
  <strong>Ongkos:</strong>
  <%= @harga.ongkos %>
</p>

<%= link_to 'Edit', edit_harga_path(@harga) %> |
<%= link_to 'Back', hargas_path %>